services:
  backend:
    tty: true
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    #user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: ./Dockerfile
    #entrypoint: /app/docker/backend/wsgi-entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  faceapp:
    build: .
    command: streamlit run get_name_from_camera.py
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    
  db:
    image: mongo:latest
    hostname: mongodbserver
    environment:
      - HOME=/data/db
    volumes:
      - /home/ubuntu/test/mongodb:/data/db 
    ports:
      - "27017:27017"